### ISSUE TITLE
IFFY wrong root context

### ISSUE THREAD

**Issue by NeXTs** [studentIvan/dueljs#13]
When using dueljs in a merged context (e.g. in a build pipeline merging all javascript files into one bundle (e.g. webpack)), the context will become (suprisingly!) empty object instead of window.

Because of this - plugin breaks during initialization at [L425](https://github.com/studentIvan/dueljs/blob/master/public/lib/duel.js#L425) saying `el` doesn't have `addEventListener` method

Using [window instead of this](https://github.com/studentIvan/dueljs/blob/master/public/lib/duel.js#L27) resolves issue for me, although maybe there are better solution..

**Comment by RasCarlito** [comment]
@NeXTs Ok now I have the same problem as I'm migrating my project to webpack :(

the `window` context instead of `this` does indeed fix the problem.

**Comment by studentIvan** [comment]
I just copied the solution from jQuery, now it is gonna be working
```javascript
(typeof window !== "undefined" ? window : this, function (window) {
```

**Comment by studentIvan** [comment]
I did test it in this code-style
```javascript
import duel from 'dueljs'
const ch = duel.channel('test')
```

**Comment by NeXTs** [comment]
Cool!
Just checked, everything works as expected.
Great job, thank you! 👍

**Comment by RasCarlito** [comment]
Nice @studentIvan :+1:
