### ISSUE TITLE
Issue on Microsoft Edge Browser (v20.10240.16384.0) Windows 10

### ISSUE THREAD

**Issue by toby11** [studentIvan/dueljs#8]
The master/slave functionality does not work under the Microsoft Edge browser, I have tested with the demo here :

http://dueljs.studentivan.ru/bower_components/duel/public/

This appears to be an issue with local storage as this localstorage event demo

http://html5demos.com/storage-events

also fails under Microsoft Edge.

thanks!
Toby

**Comment by studentIvan** [comment]
Tested it in 25.10586.0.0
It works properly

**Comment by toby11** [comment]
Great. Thanks!
